Mdk/baresip implementation (#27)
* First stab at incorporating baresip build

* Second try

* third try

* Fix model call issues on pi5

* Prevent and log attempts to restart mqtt client when we don't actually have a config for it yet.

* Fix incorrect psk validation on WifiConfiguration

* Beginning baresip implementation

* Incremental progress

* checkpoint before pivoting to async reimplementation of baresipy

* A new foundation

* A new foundation

* cleanup

* Add supports_color check and ifname/mac translation methods to utils

* Added some debug decorators

* Implement baresip control in agent

* Fix some logging naming issues

* Fix some async http response issus regarding encoding detection in api_client.py and core_client.py

* Implement sip tests, improve logging, overhaul tasker, improve mqtt disconnect handling

* checkpoint before Claude-ing

* Post-claude

* Checkpoint

* Rule cleanup fixes, more tests, missing files

* Shifted connection handling to the network manager, fixed debug log output

* Fixed table cleanup not happening on disconnect

* Improve shutdown logic.

* More fixes.

* Fixed lack of handling for CIDR prefixlents when deleting routes

* Fixed some cleanup and setup issues

* improve shutdown in order to fire interface cleanup, fix imports

* Improvements to shutdown logic

* Snagged some missing files

* update gitignore and iml file

* Enhanced to now add ip address routes for sip hosts for sip tests

* Add dedicated route to both tables

* pre-ndb fix

* fixed multiple default routes not working by using ndb as a fallback

* fixed dynamic sip server route additions and verified calls now work over wifi

* Shiz be working

* Shiz be working

---------

Co-authored-by: Michael Ketchel <mdk@rgnets.com>

diff --git a/.github/workflows/deploy-to-packagecloud.yml b/.github/workflows/deploy-to-packagecloud.yml
--- a/.github/workflows/deploy-to-packagecloud.yml
+++ b/.github/workflows/deploy-to-packagecloud.yml
@@ -23,16 +23,157 @@ jobs:
     uses: rgnets/wlanpi-gh-workflows/.github/workflows/get-formatted-version-string.yml@main
 
 
+  build_baresip:
+    name: build baresip
+    runs-on: ubuntu-24.04-arm
+    steps:
+      - name: Checkout baresip
+        uses: actions/checkout@v4
+        with:
+          repository: rgnets/baresip
+          ref: rgnets-custom
+
+
+
+      - name: fix flaky azure mirrors
+        if: ${{ runner.os == 'Linux' }}
+        run: |
+          sudo sed -i 's/azure\./de\./' /etc/apt/sources.list
+
+      - name: install packages
+        if: ${{ runner.os == 'Linux' }}
+        run: |
+          sudo apt-get update && sudo apt-get install -y \
+                              libasound2-dev \
+                              libavcodec-dev \
+                              libavdevice-dev \
+                              libavformat-dev \
+                              libcodec2-dev \
+                              libfdk-aac-dev \
+                              libglib2.0-dev \
+                              libgstreamer1.0-dev \
+                              libgtk-3-dev \
+                              libjack-jackd2-dev \
+                              libmosquitto-dev \
+                              libmpg123-dev \
+                              libopencore-amrnb-dev \
+                              libopencore-amrwb-dev \
+                              libopus-dev \
+                              libpulse-dev \
+                              libsndfile1-dev \
+                              libspandsp-dev \
+                              libssl-dev \
+                              libvpx-dev \
+                              libx11-dev \
+                              libwebrtc-audio-processing-dev
+
+      - uses: sreimers/pr-dependency-action@v1
+        with:
+          name: re
+          repo: https://github.com/baresip/re
+          secret: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: make re
+        run: |
+          cmake -S re -B re/build
+          cmake --build re/build -j
+          mv re ../.
+
+      - name: ldconfig
+        if: ${{ runner.os == 'Linux' }}
+        run: sudo ldconfig
+
+
+      - name: Build Baresip
+        run: |
+          cmake -B build -DCMAKE_BUILD_TYPE=Release -DAPP_MODULES_DIR=./modules -DAPP_MODULES="rgrtcpsummary"
+          cmake --build build -j
+
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: baresip_artifact
+          path: build
+          
+
   sbuild_deploy:
-    name: sbuild deploy pkg
     needs:
       - format
       - check_version
-    uses: rgnets/wlanpi-gh-workflows/.github/workflows/sbuild-deploy-pkg.yml@main
-    with:
-      pkg: wlanpi-rxg-agent
-      version: ${{ needs.format.outputs.version }}
-    secrets: inherit
+      - build_baresip
+
+    env:
+      PKG_NAME: wlanpi-rxg-agent
+      PKG_VERSION: ${{ needs.format.outputs.version }}
+
+    name: sbuild deploy pkg
+    runs-on: ubuntu-24.04-arm
+    environment: PACKAGECLOUD
+    strategy:
+      fail-fast: false
+      matrix:
+        distro: [ bullseye,bookworm ]
+        arch: [ arm64 ]
+    steps:
+      - name: Check if inputs all exist and are not empty
+        run: |
+          if [ -z "${{ env.PKG_NAME }}" ]; then
+            echo "Error: pkg string is empty"
+            exit 1
+          else:
+            echo "pkg is "${{ env.PKG_NAME }}"
+          fi
+          if [ -z "${{ env.PKG_VERSION }}" ]; then
+            echo "Error: version string is empty"
+            exit 1
+          else:
+            echo "Version is "${{ env.PKG_VERSION }}"
+          fi
+      - name: Get current date
+        id: date
+        run: echo "date=$(date -u +'%Y%m%dt%H%M%S')" >> $GITHUB_ENV
+      - name: Set package filename
+        run: |
+          echo "filename=${{ env.PKG_NAME }}_${{ env.PKG_VERSION }}~gha${{ env.date }}+${{ matrix.arch }}_${{ matrix.distro }}" >> $GITHUB_ENV
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Download baresip artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: baresip_artifact
+          path: ./wlanpi_rxg_agent/bin/baresip
+
+      - name: sbuild deb pkg for ${{ matrix.distro }}+${{ matrix.arch }}
+        uses: wlan-pi/sbuild-debian-package@main
+        id: build-debian-package
+        with:
+          distro: ${{ matrix.distro }}
+          arch: ${{ matrix.arch }}
+      - name: Archive artifacts and upload to GitHub
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.filename }}
+          path: ${{ steps.build-debian-package.outputs.deb-package }}
+      - name: Upload armhf pkg to debian/${{ matrix.distro }}
+        if: ${{ matrix.arch == 'armhf' }}
+        uses: danielmundi/upload-packagecloud@main
+        with:
+          package-name: ${{ steps.build-debian-package.outputs.deb-package }}
+          packagecloud-username: "${{ vars.PACKAGECLOUD_USER || 'wlanpi' }}"
+          packagecloud-repo: "${{ vars.PACKAGECLOUD_REPO || 'dev' }}"
+          packagecloud-distrib: debian/${{ matrix.distro }}
+          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}
+      - name: Upload arm64 pkg to debian/${{ matrix.distro }}
+        if: ${{ matrix.arch == 'arm64' }}
+        uses: danielmundi/upload-packagecloud@main
+        with:
+          package-name: ${{ steps.build-debian-package.outputs.deb-package }}
+          packagecloud-username: "${{ vars.PACKAGECLOUD_USER || 'wlanpi' }}"
+          packagecloud-repo: "${{ vars.PACKAGECLOUD_REPO || 'dev' }}"
+          packagecloud-distrib: debian/${{ matrix.distro }}
+          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}
+
 
 
 
